name: "ledger_analytics"
version: "1.0.0"
config-version: 2

profile: "ledger_analytics"

seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ledger_analytics:
    +materialized: table
    staging:
      +schema: staging
    customers:
      +schema: customers
      +grants:
        select: ["reporter_customers"]

seeds:
  ledger_analytics:
    +database: sources_prd
    csv:
      +schema: csv
    jaffle_shop:
      +schema: customers
    stripe:
      +schema: stripe
